version: '3.4'

services:
#  authservice:
#    image: ${DOCKER_REGISTRY-}authservice
#    build:
#      context: .
#      dockerfile: AuthService/Dockerfile
  
  postgres:
    image: postgres:latest
    restart: always
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    restart: always
    links:
      - postgres
    ports:
      - "8095:8080"
    environment:
      KEYCLOAK_USER : admin
      KEYCLOAK_PASSWORD: admin1234
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password